version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:${QDRANT_VERSION}
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./data:/qdrant/storage
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334

networks:
  default:
    name: qdrant_network