version: '3.8'

services:
  minio-archive:
    image: minio/minio:${MINIO_VERSION}
    ports:
      - "9010:9000"
      - "9011:9001"
    volumes:
      - ./data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ARCHIVE_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_ARCHIVE_SECRET_KEY}
    command: server /data --console-address ":9001"

networks:
  default:
    name: minio_archive_network