services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: always
    ports:
      - "8087:80"
    volumes:
      - nextcloud_config:/var/www/html/config
      - nextcloud_data:/var/www/html/data
      - nextcloud_custom_apps:/var/www/html/custom_apps
      - nextcloud_themes:/var/www/html/themes
    environment:
      # PostgreSQL configuration
      - POSTGRES_HOST=host.docker.internal
      - POSTGRES_DB=next_cloud
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0yq5h3to9
      - POSTGRES_PORT=5432
      
      # Redis configuration
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
      
      # Admin and domain settings
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - NEXTCLOUD_TRUSTED_DOMAINS=localhost host.docker.internal host.docker.internal:8087
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # OnlyOffice Document Server
  onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice
    restart: unless-stopped
    environment:
      # Database Configuration
      - DB_TYPE=${DB_TYPE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PWD=${DB_PWD}
      
      # Message Broker and Redis
      - AMQP_URI=${AMQP_URI}
      - REDIS_SERVER_HOST=${REDIS_SERVER_HOST}
      - REDIS_SERVER_PORT=${REDIS_SERVER_PORT}
      
      # Document Server Configuration
      - DOCSERVICE_CONNECTOR_PUBLIC_HOST=${DOCSERVICE_CONNECTOR_PUBLIC_HOST}
      - DOCSERVICE_CONNECTOR_PUBLIC_PORT=${DOCSERVICE_CONNECTOR_PUBLIC_PORT}
      - EXAMPLE_ENABLED=${EXAMPLE_ENABLED}
      - WOPI_ENABLED=${WOPI_ENABLED}
      - USE_UNAUTHORIZED_STORAGE=${USE_UNAUTHORIZED_STORAGE}
      
      # Security settings
      - SERVICES_COAUTHORING_REQUESTDEFAULTS_FILTERPRIVATEIP=${SERVICES_COAUTHORING_REQUESTDEFAULTS_FILTERPRIVATEIP}
      
      # S3 Storage Configuration
      - STORAGE_TYPE=${STORAGE_TYPE}
      - STORAGE_S3_ENDPOINT=${STORAGE_S3_ENDPOINT}
      - STORAGE_S3_ACCESS_KEY=${STORAGE_S3_ACCESS_KEY}
      - STORAGE_S3_SECRET_KEY=${STORAGE_S3_SECRET_KEY}
      - STORAGE_S3_REGION=${STORAGE_S3_REGION}
      - STORAGE_S3_BUCKET=${STORAGE_S3_BUCKET}
      - STORAGE_S3_KEY_PREFIX=${STORAGE_S3_KEY_PREFIX}
      - STORAGE_S3_SSL=${STORAGE_S3_SSL}
      - STORAGE_S3_FORCE_PATH_STYLE=${STORAGE_S3_FORCE_PATH_STYLE}
      - STORAGE_S3_ACL=${STORAGE_S3_ACL}
      
      # File Storage Configuration
      - STORAGE_PATH=/var/www/onlyoffice/Data
      - FILE_STORAGE_ENABLE_THROTTLING=${FILE_STORAGE_ENABLE_THROTTLING}
      - FILE_CACHE_ENABLE=${FILE_CACHE_ENABLE}
      - FILE_STORAGE_MAX_FILE_SIZE=${FILE_STORAGE_MAX_FILE_SIZE}
      - MAX_REQUEST_LENGTH=${MAX_REQUEST_LENGTH}
      
      # JWT for Nextcloud integration
      - JWT_ENABLED=true
      - JWT_SECRET=${JWT_SECRET}
      - JWT_HEADER=${JWT_HEADER}
      
      # Debug
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - onlyoffice_logs:/var/log/onlyoffice
      - onlyoffice_data:/var/www/onlyoffice/Data
    ports:
      - "8088:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  nextcloud_config:
  nextcloud_data:
  nextcloud_custom_apps:
  nextcloud_themes:
  onlyoffice_logs:
  onlyoffice_data: